# @file        Makefile
# @brief       The current directory Makefile
# @details     Compile the current directory link files
# @author      wangjingfan726@gmail.com
# @date        2022-12-10
# @version     v0.0.1

extra-${CONFIG_V20X_D6} += ld/$(LINK_SCRIPT).S
