# @file        Makefile
# @brief       The outermost Makefile
# @details     The root Makefile to compile the project
# @author      wangjingfan726@gmail.com
# @date        2023-02-12
# @version     v0.0.1

obj-$(CONFIG_V20X_D6) += core/core_riscv.c
obj-$(CONFIG_V20X_D6) += core/debug.c
obj-$(CONFIG_V20X_D6) += core/system_ch32v20x.c
obj-$(CONFIG_V20X_D6) += core/startup_ch32v20x_D6.S
