# @file        Makefile
# @brief       The outermost Makefile
# @details     The root Makefile to compile the project
# @author      wangjingfan726@gmail.com
# @date        2023-02-12
# @version     v0.0.1

obj-$(CONFIG_V20X_ADC)    += peri/ch32v20x_adc.c
obj-$(CONFIG_V20X_BPK)    += peri/ch32v20x_bpk.c
obj-$(CONFIG_V20X_CAN)    += peri/ch32v20x_can.c
obj-$(CONFIG_V20X_CRC)    += peri/ch32v20x_crc.c
obj-$(CONFIG_V20X_DBGMCU) += peri/ch32v20x_dbgmcu.c
obj-$(CONFIG_V20X_DMA)    += peri/ch32v20x_DMA.c
obj-$(CONFIG_V20X_EXIT)   += peri/ch32v20x_exit.c
obj-$(CONFIG_V20X_FLASH)  += peri/ch32v20x_flash.c
obj-$(CONFIG_V20X_GPIO)   += peri/ch32v20x_gpio.c
obj-$(CONFIG_V20X_I2C)    += peri/ch32v20x_i2c.c
obj-$(CONFIG_V20X_IWDG)   += peri/ch32v20x_iwdg.c
obj-$(CONFIG_V20X_MISC)   += peri/ch32v20x_misc.c
obj-$(CONFIG_V20X_OPA)    += peri/ch32v20x_opa.c
obj-$(CONFIG_V20X_PWR)    += peri/ch32v20x_pwr.c
obj-$(CONFIG_V20X_RCC)    += peri/ch32v20x_rcc.c
obj-$(CONFIG_V20X_RTC)    += peri/ch32v20x_rtc.c
obj-$(CONFIG_V20X_SPI)    += peri/ch32v20x_spi.c
obj-$(CONFIG_V20X_TIM)    += peri/ch32v20x_tim.c
obj-$(CONFIG_V20X_USART)  += peri/ch32v20x_usart.c
obj-$(CONFIG_V20X_WWDG)   += peri/ch32v20x_wwdg.c
