# @file        Makefile
# @brief       The outermost Makefile
# @details     The root Makefile to compile the project
# @author      wangjingfan726@gmail.com
# @date        2023-02-06
# @version     v0.0.1

obj-y += user/main.c
